### ISSUE TITLE
apertium-tat.tat.mb.rlx must be installed

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-tat#1]
tat-eng errors out with:
`make[1]: *** No rule to make target '/usr/share/apertium/apertium-tat/apertium-tat.tat.mb.rlx', needed by 'tat-eng.mb.rlx.bin'.  Stop.`

`apertium-tat.tat.mb.rlx` was added to the project and dependents, but isn't part of the install target. Must be added to install.

**Comment by IlnarSelimcan** [comment]
Should be fixed now: https://github.com/apertium/apertium-tat/commit/2adb08ed0e6dc30398676105e60f11b6dfcb82ed

**Comment by jonorthwash** [comment]
@TinoDidriksen, could you confirm that this is fixed?

**Comment by TinoDidriksen** [comment]
Yup, seems fixed. Dunno why I didn't notice the other comment.
