### ISSUE TITLE
incorrect "халк" instead of "халык"

### ISSUE THREAD

**Issue by mansayk** [apertium/apertium-tat#15]
`^халкым/халк<n><sg><sg><px1sg><nom>$ ^минем/мин<n><sg><sg><px1sg><nom>$`

**Comment by jonorthwash** [comment]
So this issue as well as #16 and #17 seem to have been introduced by a bunch of nouns starting on line 23280:

```
! auto translated from http://lcph.bashedu.ru/index.php?go=wikilist_lemmas
```

Is this open source data?  It seems to be in desperate need of being checked.  There are a whole bunch of other "stems" there than end in г :(

@IlnarSelimcan, do you have any thoughts on this?
