### ISSUE TITLE
күлә instead of күләм

### ISSUE THREAD

**Issue by mansayk** [apertium/apertium-tat#18]
`^күләмдәге/күлә<n><sg><sg><px1sg><loc><subst><nom>$`

**Comment by jonorthwash** [comment]
@mansayk, what is the context for this word, and what command did you use to get the analysis?

I believe both analyses are possible, and the transducer should return both.  If you're running it through the disambiguator (tagger) as well, then you need to provide some context for it to perform accurately—if there's no surrounding text, then it essentially just guesses.

**Comment by mansayk** [comment]
`echo "күләмдәге" | apertium-destxt -n | lt-proc -z -w 'apertium-tat/tat.automorf.bin' | cg-proc -z 'apertium-tat/tat.rlx.bin' | cg-proc -z -w -1 'apertium-tat/dev/mansur.bin' | apertium-retxt
^күләмдәге/күлә<n><sg><sg><px1sg><loc><subst><nom>$`

I don't remember the context of that exact case, but for example, it might be:
"Бик зур күләмдәге эш башкарылган!" ("A lot of work has been done.")

**Comment by mansayk** [comment]
And there is no word "күлә" in Tatar language and I think it should not be returned at all.

**Comment by jonorthwash** [comment]
@IlnarSelimcan, do you know why күлә is in the transducer?

**Comment by mansayk** [comment]
I just saw your message in another threat about Use/Arch not being implemented yet. So my previous question has an answer now.

**Comment by mansayk** [comment]
I disabled this word temporarily.
