### ISSUE TITLE
бунтарь, бунтарьлар

### ISSUE THREAD

**Issue by mansayk** [apertium/apertium-tat#23]
```
echo "бунтарьлар" | apertium-destxt -n | lt-proc -z -w 'apertium-tat/tat.automorf.bin' | cg-proc -z 'apertium-tat/tat.rlx.bin' | cg-proc -z -w -1 'apertium-tat/dev/mansur.bin' | apertium-retxt
^бунтарьлар/*бунтарьлар$

echo "бунтарь" | apertium-destxt -n | lt-proc -z -w 'apertium-tat/tat.automorf.bin' | cg-proc -z 'apertium-tat/tat.rlx.bin' | cg-proc -z -w -1 'apertium-tat/dev/mansur.bin' | apertium-retxt
^бунтарь/бунтарь<n><sg><nom>$
```

**Comment by mansayk** [comment]
I think this one is also connected with this case:
```
echo "валерьян" | apertium-destxt -n | lt-proc -z -w 'apertium-tat/tat.automorf.bin' | cg-proc -z 'apertium-tat/tat.rlx.bin' | cg-proc -z -w -1 'apertium-tat/dev/mansur.bin' | apertium-retxt
^валерьян/валерьян<n><sg><nom>$

echo "валерьянны" | apertium-destxt -n | lt-proc -z -w 'apertium-tat/tat.automorf.bin' | cg-proc -z 'apertium-tat/tat.rlx.bin' | cg-proc -z -w -1 'apertium-tat/dev/mansur.bin' | apertium-retxt
^валерьянны/*валерьянны$
```

**Comment by mansayk** [comment]
```
echo "вареньегыз" | apertium-destxt -n | lt-proc -z -w 'apertium-tat/tat.automorf.bin' | cg-proc -z 'apertium-tat/tat.rlx.bin' | cg-proc -z -w -1 'apertium-tat/dev/mansur.bin' | apertium-retxt
^вареньегыз/*вареньегыз$

echo "варенье" | apertium-destxt -n | lt-proc -z -w 'apertium-tat/tat.automorf.bin' | cg-proc -z 'apertium-tat/tat.rlx.bin' | cg-proc -z -w -1 'apertium-tat/dev/mansur.bin' | apertium-retxt
^варенье/варенье<n><sg><nom>$
```

**Comment by mansayk** [comment]
```
echo "декольтесы" | apertium-destxt -n | lt-proc -z -w 'apertium-tat/tat.automorf.bin' | cg-proc -z 'apertium-tat/tat.rlx.bin' | cg-proc -z -w -1 'apertium-tat/dev/mansur.bin' | apertium-retxt
^декольтесы/*декольтесы$

echo "декольте" | apertium-destxt -n | lt-proc -z -w 'apertium-tat/tat.automorf.bin' | cg-proc -z 'apertium-tat/tat.rlx.bin' | cg-proc -z -w -1 'apertium-tat/dev/mansur.bin' | apertium-retxt
^декольте/декольте<n><sg><nom>$
```

**Comment by mansayk** [comment]
```
echo "дельфинны" | apertium-destxt -n | lt-proc -z -w 'apertium-tat/tat.automorf.bin' | cg-proc -z 'apertium-tat/tat.rlx.bin' | cg-proc -z -w -1 'apertium-tat/dev/mansur.bin' | apertium-retxt
^дельфинны/*дельфинны$

echo "дельфин" | apertium-destxt -n | lt-proc -z -w 'apertium-tat/tat.automorf.bin' | cg-proc -z 'apertium-tat/tat.rlx.bin' | cg-proc -z -w -1 'apertium-tat/dev/mansur.bin' | apertium-retxt
^дельфин/дельфин<n><sg><nom>$
```

**Comment by mansayk** [comment]
This list is going to be endless... So I think some rules should be fixed and it will fix other similar problems.

**Comment by jonorthwash** [comment]
@mansayk, Could you make a short table like this for all the examples you find?  It'll help me sort out what the problems are.

analysis | expected form | current form
-----------|-------------------|-----------
`бунтарь<n><sg><nom>` | бунтарьләр | #бунтарь

**Comment by mansayk** [comment]
Analysis for base form | correct form that not analyzed
-----------------------------|---------------------------------------
`^бунтарь/бунтарь<n><sg><nom>$` | `^бунтарьлар/*бунтарьлар$`
`^валерьян/валерьян<n><sg><nom>$` | `^валерьянны/*валерьянны$`
`^варенье/варенье<n><sg><nom>$` | `^вареньегыз/*вареньегыз$`
`^декольте/декольте<n><sg><nom>$` | `^декольтесы/*декольтесы$`
`^дельфин/дельфин<n><sg><nom>$` | `^дельфинны/*дельфинны$`
`^конъюнктивит/конъюнктивит<n><sg><nom>$` | `^конъюнктивитны/*конъюнктивитны$`
`^объектив/объектив<adj>$` | `^объективрак/*объективрак$`
`^шәфәкъ/шәфәкъ<n><sg><nom>$` | `^шәфәкъны/*шәфәкъны$`
`^шәфәкъ/шәфәкъ<n><sg><nom>$` | `^шәфәгы/*шәфәгы$`

**Comment by jonorthwash** [comment]
Could you add the currently output forms to the table too?  This is important for sorting the patterns that need to be fixed.

**Comment by mansayk** [comment]
Analysis for base form | correct form that not analyzed
-----------------------------|---------------------------------------
`^валерьян/валерьян<n><sg><nom>$` | `^валерьянны/*валерьянны$`
`^шәфәкъ/шәфәкъ<n><sg><nom>$` | `^шәфәкъны/*шәфәкъны$`
`^шәфәкъ/шәфәкъ<n><sg><nom>$` | `^шәфәгы/*шәфәгы$`

**Comment by jonorthwash** [comment]
Could you test what the currently output forms are for those?  I can do it too, but this is something that will be useful for you in the future.

**Comment by mansayk** [comment]
I'm sorry, could you give me an example?

**Comment by jonorthwash** [comment]
@mansayk, I edited the first line of the table to a much more useful format.  Could you convert the other lines to this format?
