### ISSUE TITLE
Verb form аера not analysed

### ISSUE THREAD

**Issue by ftyers** [apertium/apertium-tat#3]
Trying to analyse the following sentence: "Көньяк чик башта Ур муенын кисеп үтә, Каркинит култыгын, аннан соң Кара диңгез буйлап бара, аннан Адлер янында тауларга күтәрелә һәм Зур Кавказның Субүләр сырты буенча Русияне Гөрҗистаннан һәм Азәрбайҗаннан аера."

```
fran@matxine:~/source/apertium/languages/apertium-tat$ echo "аер<v><tv><pres><p3><sg>" | hfst-lookup .deps/tat.LR.lexc.hfst 
аер<v><tv><pres><p3><sg>	аер>{E}	0,000000

fran@matxine:~/source/apertium/languages/apertium-tat$ echo "аер<v><tv><pres><p3><sg>" | hfst-lookup .deps/tat.LR.hfst 
аер<v><tv><pres><p3><sg>	аерә	0,000000

```

@jonorthwash any ideas? We've tried a few hacks, but kept messing up other stuff :)

**Comment by jonorthwash** [comment]
Try it now?

**Comment by ftyers** [comment]
@jonorthwash works now, thanks! 

```
$ echo "аера" | apertium -d . tat-chv
уйӑрать
```
