### ISSUE TITLE
Vowel harmony issues with some nouns

### ISSUE THREAD

**Issue by ftyers** [apertium/apertium-tat#4]
Trying to analyse the sentence: "Төньякта Русия киң фронт белән Төньяк Боз океаны диңгезләренә чыга."

Looks like another vowel harmony problem, could be related to #3.

```
$ echo "төньяктә" | apertium -d . tat-morph
^төньяктә/төньяк<n><loc>/төньяк<n><loc>+и<cop><aor><p3><pl>/төньяк<n><loc>+и<cop><aor><p3><sg>$^./.<sent>$
```

This is also not working: _көньяктарак_ ... we're going to add `{ъ}` for now, but is that a permanent solution, @jonorthwash ?

**Comment by jonorthwash** [comment]
Yes, I believe that's the correct permanent solution in this case.  Other words of this shape would almost definitely take front-vowel endings.  The reason this word doesn't is because it's a compound, which isn't really reflected in the spelling.

**Comment by jonorthwash** [comment]
Is that answer all that's needed to close this issue?

**Comment by IlnarSelimcan** [comment]
That's a question to @ftyers , I think :)

**Comment by mansayk** [comment]
`төньякта` is fixed, but `көньяктарак` is in another issue: #5
